name = "Create Lets Create Custom"
author = "Me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e30227fb114d4905feb1fd2ece729cece15c9d732868fa3ace35d95eaf35d65"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.193"
